notifications:
  email: false

os: osx

language: c

git:
  depth: 3

env:
  - COLUMNS=78
before_install:
  - source ./macports/bootstrap.sh
script:
  - sed -i '' "s|@@REPO_PATH@@|${PWD}|g" macports/Portfile
  - sudo port destroot "file://${PWD}/macports" || (port log "file://${PWD}/macports" | tail -n 1000)
